run:
  # include test files or not, default is true
  tests: false

  skip-dirs:
    - .circleci
    - .git
    - .idea
    - bin
    - node_modules
    - tmp

linters-settings:
  errcheck:
    # report about not checking of errors in type assetions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions: true
  govet:
    # report about shadowed variables
    check-shadowing: true
    enable-all: true
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/janivihervas/authproxy
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 15
  gocognit:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 15
  misspell:
    locale: UK
#    ignore-words:
#      - someword

linters:
  enable:
    - govet # Vet examines Go source code and reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
    - errcheck # Errcheck is a program for checking for unchecked errors in go programs. These unchecked errors can be critical bugs in some cases
    - staticcheck # Staticcheck is a go vet on steroids, applying a ton of static analysis checks
    - unused # Checks Go code for unused constants, variables, functions and types
    - gosimple # Linter for Go source code that specializes in simplifying a code
    - structcheck # Finds unused struct fields
    - varcheck # Finds unused global variables and constants
    - ineffassign # Detects when assignments to existing variables are not used
    - deadcode # Finds unused code

    - bodyclose # checks whether HTTP response body is closed successfully
    - golint # Golint differs from gofmt. Gofmt reformats Go source code, whereas golint prints out style mistakes
    - gosec # Inspects source code for security problems
    - interfacer # Linter that suggests narrower interface types
    - unconvert # Remove unnecessary type conversions
    - dupl # Tool for code clone detection
    - goconst # Finds repeated strings that could be replaced by a constant
    - gocyclo # Computes and checks the cyclomatic complexity of functions
    - gocognit # Computes and checks the cognitive complexity of functions
    - misspell # Finds commonly misspelled English words in comments
    - unparam # Reports unused function parameters
    - dogsled # Checks assignments with too many blank identifiers (e.g. x, _, _, _, := f())
    - nakedret # Finds naked returns in functions greater than a specified function length
    - prealloc # Finds slice declarations that could potentially be preallocated
    - scopelint # Scopelint checks for unpinned variables in go programs
    - gocritic # The most opinionated Go source code linter
    - funlen # Tool for detection of long functions

  disable:
    - typecheck # Like the front-end of a Go compiler, parses and type-checks Go code
    - stylecheck # Stylecheck is a replacement for golint
    - gofmt # Gofmt checks whether code was gofmt-ed. By default this tool runs with -s option to check for code simplification
    - goimports # Goimports does everything that gofmt does. Additionally it checks unused imports
    - maligned # Tool to detect Go structs that would take less memory if their fields were sorted
    - godox # Tool for detection of FIXME, TODO and other comment keywords
    - gochecknoinits # Checks that no init functions are present in Go code
    - gochecknoglobals # Checks that no globals are present in Go code
    - depguard # Go linter that checks if package imports are in a list of acceptable packages
    - lll # Reports long lines
    - whitespace # Tool for detection of leading and trailing whitespace
    - wsl # Whitespace Linter - Forces you to use empty lines!

  fast: false
